apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort  # Exposes the app externally in Minikube
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000        # Internal Kubernetes service port
      targetPort: 5000  # Flask app running inside the container
      nodePort: 30007   # External Minikube port (must be between 30000-32767)
